name: AOSP-STUFF
on:
  schedule:
    - cron: "0 0 * * mon"
    - cron: "0 0 * * wed"
    - cron: "0 0 * * fri"
    - cron: "0 0 * * sun"
  workflow_dispatch:
  
env:
  GIT_PASS: ${{ secrets.GIT_PASS }}
  TZ: Asia/Kolkata
  
jobs:
  job1:
    name: Update Binary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Script
      run: curl -LO https://raw.githubusercontent.com/Jrchintu/external_bromite-webview/R11/update.sh && chmod a+x ./update.sh && ./update.sh
    - uses: gautamkrishnar/keepalive-workflow@master # using the workflow with default settings
